//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoA.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/cargarCiudades", ReplyAction="http://tempuri.org/IService1/cargarCiudadesResponse")]
        string[] cargarCiudades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/cargarCiudades", ReplyAction="http://tempuri.org/IService1/cargarCiudadesResponse")]
        System.Threading.Tasks.Task<string[]> cargarCiudadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ingresarTablaWeb", ReplyAction="http://tempuri.org/IService1/ingresarTablaWebResponse")]
        void ingresarTablaWeb(string nom, string ape, string sex, string ema, string dir, string ciu, string req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ingresarTablaWeb", ReplyAction="http://tempuri.org/IService1/ingresarTablaWebResponse")]
        System.Threading.Tasks.Task ingresarTablaWebAsync(string nom, string ape, string sex, string ema, string dir, string ciu, string req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarNombre", ReplyAction="http://tempuri.org/IService1/consultarNombreResponse")]
        bool consultarNombre(string nom, string ape);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarNombre", ReplyAction="http://tempuri.org/IService1/consultarNombreResponse")]
        System.Threading.Tasks.Task<bool> consultarNombreAsync(string nom, string ape);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProyectoA.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProyectoA.ServiceReference1.IService1>, ProyectoA.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] cargarCiudades() {
            return base.Channel.cargarCiudades();
        }
        
        public System.Threading.Tasks.Task<string[]> cargarCiudadesAsync() {
            return base.Channel.cargarCiudadesAsync();
        }
        
        public void ingresarTablaWeb(string nom, string ape, string sex, string ema, string dir, string ciu, string req) {
            base.Channel.ingresarTablaWeb(nom, ape, sex, ema, dir, ciu, req);
        }
        
        public System.Threading.Tasks.Task ingresarTablaWebAsync(string nom, string ape, string sex, string ema, string dir, string ciu, string req) {
            return base.Channel.ingresarTablaWebAsync(nom, ape, sex, ema, dir, ciu, req);
        }
        
        public bool consultarNombre(string nom, string ape) {
            return base.Channel.consultarNombre(nom, ape);
        }
        
        public System.Threading.Tasks.Task<bool> consultarNombreAsync(string nom, string ape) {
            return base.Channel.consultarNombreAsync(nom, ape);
        }
    }
}
